export const CY_LOCATORS = {
	BUTTON__CLOSE_DRAWER: 'button-exit',
	BUTTON__SAVE: 'button-save',
	BUTTON_CLEAR: 'button-clear',
	CHOSE_PROVIDER_SECTION: 'chose-provider-section',
	DIALOG_BUTTON__CANCEL: 'dialog-button_cancel',
	DIALOG_BUTTON__YES: 'dialog-button_yes',
	DIALOG_CONTAINER: 'dialog-container',
	DIALOG_CONTAINER__CONTENT: 'dialog-container_content',
	DIALOG_CONTAINER__TITLE: 'dialog-container_title',
	DRAWER_HEADER: 'drawer-header',
	DRAWER_HEADER__TITLE: 'drawer-header__title',
	LOADER: 'loader',
	MENU_ITEM: 'menu-item',
	NOTIFICATION_SNACKBAR: 'notification-snackbar',
	NOTIFICATION_CONTENT: 'notification-content',
	PROVIDER_FIELD_DROPDOWN_TYPE: 'provider-field-dropdown-type',
	PROVIDER_FIELD_TEXT_TYPE: 'provider-field-text-type',
	PROVIDER_FIELD_TOGGLE_TYPE: 'provider-field-toggle-type',
	PROVIDER_FIELDS_SECTION: 'provider-fields-section',
	SELECTOR_DROPDOWN: 'selector-dropdown',
	SELECTOR_FORM: 'selector-form',
	SELECTOR_INPUT: 'selector-input',
	SELECTOR_TOOLTIP: 'selector-tooltip',
	SELECTOR__VALIDATION_TEXT: 'selector__validation-text',
	SWITCH_BUTTON__TITLE: 'switch-button_title',
	SWITCH_BUTTON__TOGGLE: 'switch-button_toggle',
};
