export const STRINGS = {
	alert: 'Alert',
	cancel: 'Cancel',
	cancelDialogText: 'You have unsaved changes that will be lost. Would you like to discard the changes?',
	choose: 'Choose',
	chooseProvider: 'Choose provider',
	clear: 'Clear',
	confirm: 'Confirm',
	continue: 'Continue',
	disabled: 'Disabled',
	disableDialogText: 'Are you sure you would like to disable this provider?',
	enabled: 'Enabled',
	enableDialogText: 'Are you sure you would like to enable this provider?',
	error: 'error',
	fieldRequired: 'This field is required',
	openLoyaltyConfiguration: 'Open Loyalty Configuration',
	previouslyEnabledProviderText: 'The previous loyalty provider will be disabled upon saving these changes. ' +
		'Do you wish to continue with the new loyalty provider?',
	provider: 'Provider',
	providerSetup: 'Provider setup',
	save: 'Save',
	somethingWentWrong: 'Something went wrong! Please try again.',
	warning: 'Warning',
	yes: 'Yes',
	mockProvider1: 'mock-provider-1',
	mockProvider2: 'mock-provider-2',
};
